main: com.kolinkrewinkel.BitLimitPvP.BitLimitPvP
name: BitLimit PvP
version: ${project.version}
author: Kolin Krewinkel
description: BitLimit PVP Plugin
commands:
  bitlimit:
    description: unimplemented
    usage: /<command> [message]
    permission: sample.message
permissions:
  bitlimit.*:
    description: gives all permissions of BitLimit PvP
    default: op
    children:
      bitlimit.message:
        description: gives permission to set the sample message using the sample command