main: com.bitlimit.kolinkrewinkel.BitLimitPVP
name: BitLimit PVP
version: ${project.version}
author: Kolin Krewinkel
description: BitLimit PVP Plugin
commands:
  sample:
    description: unimplemented
    usage: /<command> [message]
    permission: sample.message
permissions:
  sample.*:
    description: gives all permissions of the SamplePlugin
    default: op
    children:
      sample.message:
        description: gives permission to set the sample message using the sample command