main: com.kolinkrewinkel.BitLimitPvP.BitLimitPvP
name: BitLimit PvP
version: 0.2.0
author: Kolin Krewinkel
description: BitLimit PvP - Map, team, match, and statistics manager for Minecraft PvP.
website: http://github.com/kolinkrewinkel/BitLimitPvP/
commands:
    map:
        description: WIP - Map management
    team:
        description: WIP - Manages team members
    match:
        description: WIP - Match info
    stats:
        description: WIP - Statistics

permissions:
    bitlimit.*:
        description: gives all permissions of BitLimit PvP
        default: op
        children:
            bitlimit.stats:
                description: gives permission to retrieve stats