main: com.kolinkrewinkel.BitLimitPvP.BitLimitPvP
name: BitLimit PvP
version: 0.1.0
author: Kolin Krewinkel
description: BitLimit PVP Plugin
website: http://github.com/kolinkrewinkel/BitLimitPvP/
softdepend: [WorldGuard]
commands:
  map:
    description: WIP - Controls Maps used by BitLimit PvP
  team:
    description: WIP - Team info used by BitLimit PvP
  match:
    description: WIP - Match info used by BitLimit PvP
  admin:
    description: WIP - Admin commands used by BitLimit PvP

permissions:
  bitlimit.*:
    description: gives all permissions of BitLimit PvP
    default: op
    children:
      bitlimit.message:
        description: gives permission to set the sample message using the sample command