main: com.kolinkrewinkel.BitLimitPvP.BitLimitPvP
name: BitLimit PvP
version: 0.0.5
author: Kolin Krewinkel
description: BitLimit PVP Plugin
commands:
  sample:
    description: unimplemented
    usage: /<command> [message]
    permission: sample.message
permissions:
  sample.*:
    description: gives all permissions of BitLimit PvP
    default: op
    children:
      sample.message:
        description: gives permission to set the sample message using the sample command